import 'package:flutter/material.dart';
import 'package:flutter_assignment/helper.dart';
import 'package:flutter_assignment/model/moviedata.dart';
import 'package:provider/provider.dart';
import 'viewpage.dart';
import 'package:flutter_assignment/provider/providerfile.dart';
import 'package:flutter_assignment/model/httpmodel.dart';
class SearchScreen extends StatefulWidget {
  const SearchScreen({Key? key}) : super(key: key);

  @override
  _SearchScreenState createState() => _SearchScreenState();
}

class _SearchScreenState extends State<SearchScreen> {



  getvalue() async {
    var provider = Provider.of<HomePageProvider>(context,listen: false);
    var respone = await APIHelper.getPosts();
    if(respone.isSuccessful)
      {
        provider.setdata(respone.data);
      }
    else{

    }
}

@override
  void initState() {
    // TODO: implement initState
    super.initState();
    getvalue();
  }

  TextEditingController controller =TextEditingController();
  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Scaffold(
backgroundColor: Color(0xFF210F37),
        body: Container(
        decoration: BoxDecoration(
          // gradient: LinearGradient(
          //   colors: [
          //     Color(0xFF17082A),
          //     Color(0xFF210F37),
          //   ],
          //   end: Alignment.bottomRight,
          //   begin: Alignment.topLeft
          // ),
          image: DecorationImage(
            image: AssetImage("assets/bg bloop.png")
          ),

        ),
         child: Column(
           mainAxisAlignment: MainAxisAlignment.start,
           crossAxisAlignment: CrossAxisAlignment.stretch,
           children: [
             Padding(
               padding: const EdgeInsets.only(left: 20.0,top: 35,right: 18),
               child: Container(
                 width: 335,
                 height: 50,
                 decoration: BoxDecoration(
                    color: Color(0xFF483c56),
                    borderRadius: BorderRadius.circular(15)
                 ),
                 child: Padding(
                   padding: const EdgeInsets.all(8.0),
                   child: TextField(
controller: controller,
                     cursorColor: Colors.black,
                     style: TextStyle(color: Colors.white),
                     keyboardType: TextInputType.text,
                     decoration: new InputDecoration(
                       prefixIcon: Image.asset("assets/Frame.png"),
                         border: InputBorder.none,
                         focusedBorder: InputBorder.none,
                         enabledBorder: InputBorder.none,
                         errorBorder: InputBorder.none,
                         disabledBorder: InputBorder.none,
                         contentPadding:
                         EdgeInsets.only(left: 15, bottom: 11, top: 11, right: 15),
                         hintText: "Search"),
                   ),
                 ),
               ),
             ),
             SizedBox(height: 15,),
             // searchwidget()
            Expanded(
              child: SizedBox(
                child: Consumer<HomePageProvider>(builder: (_,provider,__){
                  return ListView.builder(
                    itemCount: provider.postlist.length,
                      itemBuilder: (_,index)
                  {
                    Autogenerated post = provider.getPostByIndex(index);
                    return searchwidget(image: post.poster,rating: post.imdbRating,moviename: post.title,released: post.released,gner: post.genre,);
                  });
                }),
              ),
            )
           ],
         ),
        ),
      ),
    );

  }
}

class searchwidget extends StatelessWidget {

  final String image;
  final String moviename;
  final String rating;
  final String released;
  final String gner;
  searchwidget({required this.image,required this.rating,required this.moviename, required this.released, required this.gner});


  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: ()
      {
        Navigator.push(context, MaterialPageRoute(builder: (context)
        {
          return ViewPage(image: image,name: moviename,rating: rating,gner: gner,);
        }));
      },
      child: Padding(
        padding: const EdgeInsets.only(left: 18.0,right: 18),
        child: Container(
          width: 390,
          height: 350,
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(10),
          ),
          child: Stack(

              children: [

                Column(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.stretch,
                  children: [
                    ClipRRect(

                      borderRadius: BorderRadius.circular(40),

                      child: Image(
                        image: NetworkImage(
                            image),
                        width: 390,
                        height: 250,
                        fit: BoxFit.fill,
                      ),
                    ),
                    Padding(
                      padding: const EdgeInsets.only(left: 28.0),
                      child: Text(moviename,style: TextStyle(color: Colors.white,fontSize: 18,fontFamily: "Schyler"),),
                    ),
                    SizedBox(height: 5,),
                    Padding(
                      padding: const EdgeInsets.only(left: 28.0),
                      child: Row(
                        children: [
                          Image.asset('assets/Group 356.png',width: 20,height: 20,),
                          SizedBox(width: 15,),
                          Text(released,style: TextStyle(color: Color(0xFFF79E44),fontSize: 15,fontFamily: "Schyler"),),
                        ],
                      ),
                    ),
                  ],
                ),
                Positioned(
                  top: 30,
                  left: 30,
                  child: InkWell(

                    child: Container(
                      width: 40,
                      height: 20,
                      decoration: BoxDecoration(
                          color: Colors.white.withOpacity(0.5),
                          borderRadius: BorderRadius.circular(5)
                      ),
                      child: Center(child: Text(rating)),
                    ),
                  ),
                ),
              ]
        )),
      ),
    );
  }
}


