import 'package:flutter/foundation.dart';
import 'package:flutter_assignment/model/moviedata.dart';

class HomePageProvider extends ChangeNotifier {
  bool _isHomePageProcessing = true;
  List<Autogenerated> _postsList = [];
  bool _shouldRefresh = true;

  List<Autogenerated> get postlist => _postsList;

  setdata(List<Autogenerated> list)
  {
    _postsList = list;
    notifyListeners();
  }

  Autogenerated getPostByIndex(int index) => _postsList[index];
}